---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vaulidate-native
    namespace: vaulidate-native
    labels:
      app: vaulidate-native
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: vaulidate-native
    template:
      metadata:
        namespace: vaulidate-native
        labels:
          app: vaulidate-native
      spec:
        containers:
        - name: vaulidate
          image: wallacepf/vaulidate:latest
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc:8200"
            - name: VAULT_MODE
              value: "native"
            - name: ROLE_ID
              value: "f0103032-a54c-0654-a21a-502c09f4f901"
            - name: SECRET_ID
              value: "4ca6d0d0-0f6a-8646-f0e3-548a7e61e5e9"
            - name: SECRET_PATH
              value: "secret/data/vaulidate/mysecret"

---
apiVersion: v1
kind: Service
metadata:
  name: vaulidate-native
  namespace: vaulidate-native
spec:
  type: LoadBalancer
  selector:
    app: vaulidate-native
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080

# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: validate
#   namespace: vaulidate
# spec:
#   path: /
#   to:
#     kind: Service
#     name: vaulidate
#   port:
#     targetPort: 8080

