name: Publish Docker Image DockerHub
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish_to_registries:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://144.22.219.26
          tlsSkipVerify: true
          method: approle
          roleId: ${{ secrets.ROLE_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          secrets: |
              secret/data/gha/dh_creds dh_username | DH_USERNAME ;
              secret/data/gha/dh_creds dh_password | DH_PASSWORD ;
              secret/data/gha/vaulidate username | VAL_USERNAME ;
              secret/data/gha/vaulidate password | VAL_PASSWORD ;
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Log in DockerHub
        uses: docker/login-action@v1
        with:
          username: $DH_USERNAME
          password: $DH_PASSWORD
      - name: Push to DH
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            "var_username=$VAL_USERNAME"
            "var_password=$VAl_PASSWORD"
          tags: wallacepf/vaulidate:gha